# Generated by Django 5.1.4 on 2025-02-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('sessions', models.CharField(choices=[('session_morning', 'Morning Session'), ('session_afternoon', 'Afternoon Session'), ('session_evening', 'Evening Session')], max_length=20)),
                ('dietary', models.CharField(choices=[('none', 'No Preference'), ('veg', 'Vegetarian'), ('vegan', 'Vegan'), ('gf', 'Gluten-Free')], max_length=20)),
            ],
        ),
    ]
